### ISSUE TITLE
Only work for email of gmail.com

### ISSUE THREAD

**Issue by thanhdc247** [kakshay21/verify_email#34]
Please check your lib, I have checked your lib but it only work fine for gmail.com :(

**Comment by kakshay21** [comment]
hey @thanhdc247, can you be a little more specific? as I've tried with other emails and it works.

**Comment by thanhdc247** [comment]
Hi @kakshay21, you could try outlook.com yahoo.com or another domain using gsuite service.

**Comment by kakshay21** [comment]
Hey @thanhdc247, it's working fine for other domains using gsuite service, but yeah observed this in with yahoo emails.
Thanks for reporting, will work on the fix soon.

**Comment by Danilka** [comment]
Noticed the same thing.
For me, it always fails @icloud.com @att.net 
@hotmail.com is failed only sometimes.

**Comment by Danilka** [comment]
You can pass verify=False to disable domain verification while this is being fixed.
`verify_email('user@example.com', verify=False)`

**Comment by Danilka** [comment]
I ran a few tests on my local computer and could not reproduce the issue. Though I noticed that at some point Apple (@icloud.com) starts throttling the requests. I bet that at some point they just stop replying to the smtp.rcpt() request.

It's not really clear how does one fix this.

**Comment by kakshay21** [comment]
yes @Danilka, I noticed that too, from my understanding they're blacklisting the IP used for the request, which is a very tricky problem to solve.

**Comment by Danilka** [comment]
I'd be happy to contribute to the project if we agree on a strategy.
One of the ideas is to detect the blockage and fallback on basic validation instead.

**Comment by kakshay21** [comment]
yeah @Danilka, and detection would start from mapping all the SMTP errors code, I didn't pay much attention to this earlier.
have a look at https://serversmtp.com/smtp-error/
Please feel free to make a PR for any resolution that comes to your mind.

**Comment by tjacksonpari** [comment]
I try run python examples.py 
My Errors in attack file
![1](https://user-images.githubusercontent.com/59942212/79830876-87066180-83d0-11ea-870b-66f6d566ebd1.PNG)
How to fix it?I use win 7 64bit

**Comment by kakshay21** [comment]
Hey @tjacksonpari 
it's strange that your python environment is invoking cffi module. Probably the python you installed doesn't have the full support for asyncio library which I'm using in this package.
can you verify if you're using the python from https://www.python.org/downloads/windows/ ?

**Comment by ebizanil** [comment]
It is not working for a domain-specific email address, office address, anil@thinkebiz.net it says false, but it exists.

**Comment by kakshay21** [comment]
@ebizanil, sure it's a known bug, I'll try to complete in the incoming weekend. thanks!

**Comment by Mwatchorn26** [comment]
@kakshay21 I'm running Windows 10, and ran into the same issue. I had to:
```
from verify_email import verify_email
import aiodns
import asyncio
import sys
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
verify_email('someone@example.com')
```

**Comment by Mwatchorn26** [comment]
I've found yahoo.com does work [for me], but the Microsoft related servers I've tried do no work. 
Hotmail and Office365 both fail.

**Comment by kakshay21** [comment]
I think most of the errors should go now after the latest release, please feel free to open this.
Also, please add the logs which help a lot in the investigation.
