### ISSUE TITLE
Can I bypass SMTP test?

### ISSUE THREAD

**Issue by r1235613** [kakshay21/verify_email#39]
Some mail server use [Greylisting](https://en.wikipedia.org/wiki/Greylisting_(email)).
Greylisting will reject all first requests and wait for a period of time before accepting a second attempt.
Can you provide some options to skip the SMTP test (even if the results are less accurate) to avoid the problem that it will definitely fail the first time?

If you need a case, you can test my email (r1235613@lv5.in), it will wait 300 seconds for the first request.

**Comment by kakshay21** [comment]
sure, you can skip by providing verify=False as one of the parameters.
