### ISSUE TITLE
There is no current event loop in thread 'Thread-2'.

### ISSUE THREAD

**Issue by Muhammedsuwaneh** [kakshay21/verify_email#41]
There is no current event loop in thread 'Thread-2'. I am getting this error whenever I try to verify an email in django

**Comment by kakshay21** [comment]
Hi @Muhammedsuwaneh, thanks for reporting!
Can you also send the stack trace? With environment configuration like python version, django version?

**Comment by harishsg99** [comment]
Hey I am also getting the  same error on django, is there any workaround?

**Comment by Muhammedsuwaneh** [comment]
I haven't figured out a solution yet.

**Comment by kakshay21** [comment]
Can you guys try the 2.4.4 version and see if it works?
`pip3 install verify-email==2.4.4.dev0`

**Comment by afsar47** [comment]
this problem is not related to verify_email package  are you using a web server like Django and Flask so you should be register loop event like this

```
import asyncio
 asyncio.set_event_loop(asyncio.new_event_loop())
           for row in data.itertuples():
          
            try:
                print(row.Email)
                emails.append(row.Email)
                verified_emails.append(verify_email(row.Email))
            except Exception as e:
                print(e)
```
 it's work for me
