### ISSUE TITLE
Email Verification does not work in a separate thread.

### ISSUE THREAD

**Issue by JacobHagberg** [kakshay21/verify_email#46]
If I create a new thread and try to verify an email in that thread, it does not work.
Error:
RuntimeError: There is no current event loop in thread 'Thread-1 (ThreadTarget)'.

**Comment by kakshay21** [comment]
can you try once with 2.4.4 version?
`pip3 install verify-email==2.4.4.dev0`

**Comment by Avx11** [comment]
Random random = new Random();
                                    code = random.nextInt(8999)+1000;
                                    String url = "//github.com/kakshay21/verify_email";
                                    RequestQueue requestQueue = Volley.newRequestQueue(getApplicationContext());
                                    StringRequest stringRequest= new StringRequest(Request.Method.POST, url, new Response.Listener<String>() {
                                        @Override
                                        public void onResponse(String response) {
                                            Toast.makeText(OTP_Activity.this, ""+response, Toast.LENGTH_SHORT).show();

                                        }

form this code i cant use the url and i don't how to created ):

**Comment by Avx11** [comment]
I am working in android studio using java to verify Email otp

**Comment by kakshay21** [comment]
check: https://github.com/kakshay21/verify_email/issues/48#issuecomment-1685262024
